version: '3'
# lancer avec : docker-compose --env-file .env up
services:
    web:
        image: nginx:latest
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./app:/app
    php:
        build: ./docker/php/
        volumes:
            - ./app:/app
            - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        expose:
            - 9000
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
            XDEBUG_CONFIG: ${XDEBUG_CONFIG}
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./mysql-data:/var/lib/mysql
            - ./init-db:/docker-entrypoint-initdb.d
        ports:
            - "${MYSQL_PORT}:3306"
    adminer:
        container_name: adminer
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: "${ADMINER_DEFAULT_SERVER}"
        ports:
            - "${ADMINER_PORT}:8080"
volumes:
    mysql-data: {}
